### PR TITLE
Modernize and clean up

### PR DESCRIPTION
**Pull request by rotu**
Fix the build.
Bump dependencies
Remove babel, autoprefixer, @rollup/plugin-replace, @rollup/plugin-babel
replace rollup-plugin-typescript with @rollup/plugin-typescript

### CODE REVIEW

**Comment by razorness** [comment]
Hi, I will take a look into this tomorrow.

**Comment by Sieboldianus** [comment]
Tried to check this out locally and got:
```bash
error css-minimizer-webpack-plugin@3.4.1: The engine "node" is incompatible with this module. Expected version ">= 12.13.0". Got "12.10.0"
error Found incompatible module.
```

**Comment by rotu** [comment]
@razorness Could you take another look? I've switched to vite, since Vue CLI is in maintenance mode.

@Sieboldianus Node 12 is unsupported and unmaintained. I'd recommend updating. https://nodejs.org/en/download/

**Comment by rotu** [comment]
I renamed to better reflect the nature of this PR. It's not "broken" per se, but now the dev dependencies should be easier to meet. Particularly, the demo project and the actual build both use rollup (vue-cli used to use webpack).

Before:

npx howfat --dev-dependencies                             
Dependencies: 2752
Size: 294.66mb
Files: 36980

After:

npx howfat --dev-dependencies                        
Dependencies: 169
Size: 213.59mb
Files: 6266

**Comment by razorness** [comment]
Okay. I am very busy but I have to take a look on your work. Give me few days.

**Comment by rotu** [comment]
@razorness, working on anything fun?

**Comment by razorness** [comment]
@rotu I just refactored many parts of the lib, switched to vitejs and upgraded to maplibre gl js v2. I guess, there are a lot of conflicts now with your fork.

**Pull request closed without merging**
